<?
$PERM["lichnyy-kabinet-pokupatelya"]["G6"]="X";
$PERM["lichnyy-kabinet-pokupatelya"]["*"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["G1"]="X";
$PERM["lichnyy-kabinet-prodavtsa"]["G2"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["G3"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["G4"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["G6"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["G5"]="X";
$PERM["lichnyy-kabinet-prodavtsa"]["*"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["G1"]="X";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>